AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'AWS CloudFormation Template Role'
Resources:
  rCloudFormationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName : CloudFormationExecutionRole
      MaxSessionDuration : 43200
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
Outputs:
  RoleArn : Fn::GetAtt rCloudFormationRole.Arn
  RoleId : Fn::GetAtt rCloudFormationRole.RoleId

