AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'AWS CodeBuild Template Role'
Resources:
  rCodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName : CodeBuildExecutionRole
      MaxSessionDuration : 43200
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
Outputs:
  RoleArn : Fn::GetAtt rCodeBuildRole.Arn
  RoleId : Fn::GetAtt rCodeBuildRole.RoleId

